[package]
name = "acl"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = {version = "4.1.3", features=["rand_core", "digest", "group"]}
digest = "0.10.7"
group = "0.13.0"
rand_core = {version = "0.6.4", features=["getrandom"]}
sha2 = "0.10.8"
